import Link from 'next/link';
import { projects, writing, fieldNotes } from './content';
import { SocialLinks } from './components/social-links';
import { SiteIcon } from './components/site-icon';
import { IdeaNetwork } from './components/idea-network';
import { Scribble, WaveDivider, Portrait } from './components/design-elements';
import { PhotoArt } from './components/photo-art';
export default function Home() {
 return <main id="main-content" className="home-page">
  <div className="page-shell">
   <section className="portfolio-hero" aria-labelledby="hello">
    <div className="hero-copy"><p className="eyebrow">MACHINE LEARNING · ENGINEERING · CURIOSITY</p><h1 id="hello">Hi, I’m <span>Romil.<Scribble/></span></h1><p className="hero-lead">Exploring intelligence.<br/>Making useful things.</p><p className="hero-description">I’m an ML / AI engineer with a researcher’s curiosity. This is where I share what I build, what I learn, and the interesting things in between.</p><div className="hero-actions"><Link className="primary-link" href="/projects">Explore my work <SiteIcon name="arrow"/></Link><Link className="quiet-link" href="/about">A little about me <span>↗</span></Link></div><SocialLinks/></div>
    <IdeaNetwork/>
   </section>
   <section className="work-section" aria-labelledby="selected-work"><div className="section-heading"><div><p className="eyebrow">IDEAS INTO THINGS</p><h2 id="selected-work">On the workbench<span className="yellow">.</span></h2></div><Link className="quiet-link" href="/projects">All projects <span>↗</span></Link></div><div className="work-grid">{projects.slice(0,2).map((project,i) => <Link className={`work-card work-${i}`} href={`/projects/${project.slug}`} key={project.slug}><div className="work-card-top"><span className="project-mark"><SiteIcon name={i===0?'code':'compass'}/></span><span className="sample-label">Sample project</span><span className="card-arrow">↗</span></div><h3>{project.title}</h3><p>{project.copy.replace('. without', ', without')}</p><div className="tag-list">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div></Link>)}</div><p className="content-note">A preview of the project layout. Real projects are up next.</p></section>
   <WaveDivider/>
   <section className="home-writing" aria-labelledby="latest-writing"><div className="section-heading"><div><p className="eyebrow">NOTES FROM THE JOURNEY</p><h2 id="latest-writing">Learning, out loud<span className="lavender">.</span></h2></div><Link className="quiet-link" href="/writing">All writing <span>↗</span></Link></div><div className="writing-spread"><div>{writing.slice(0,3).map(post=><article className="home-post" key={post.slug}><div className="post-meta">{post.category}<span>·</span>{post.readTime}<span className="sample-label">Sample essay</span></div><h3><Link href={`/writing/${post.slug}`}>{post.title}</Link></h3><p>{post.excerpt}</p><Link className="read-link" href={`/writing/${post.slug}`}>Read the note <span>→</span></Link></article>)}</div><aside className="notebook-aside"><span className="handwritten">Always a beginner at something.</span><div className="aside-rule"/><h3>Around here</h3><ul className="arrow-list"><li><Link href="/projects">Projects & experiments</Link></li><li><Link href="/writing">Notes worth sharing</Link></li><li><Link href="/playground">Small, useful tools</Link></li><li><Link href="/field-notes">Life away from the screen</Link></li></ul><p>Some polished. Some still figuring themselves out. All part of the process.</p><span className="aside-spark" aria-hidden="true">✳</span></aside></div></section>
   <section className="playground-callout"><div className="playground-icon" aria-hidden="true">↗<span>✳</span></div><div><p className="eyebrow">A LITTLE ROOM TO PLAY</p><h2>Useful things. Just for the fun of it.</h2><p>Tiny browser tools and interactive experiments. No setup required.</p></div><Link className="quiet-link" href="/playground">Visit the playground <span>→</span></Link></section>
   <section className="home-about" aria-labelledby="home-about-title"><Portrait/><div><p className="eyebrow">THE HUMAN BEHIND THE CODE</p><h2 id="home-about-title">A little more <span className="underlined">human.<Scribble/></span></h2><p>I like understanding how things work, then making something with what I’ve learned. AI is a big part of that. So is writing things down and following a good question.</p><p>This space is also for the occasional photograph, a small detour, and life beyond a screen.</p><Link className="quiet-link" href="/about">More about me & my journey <span>↗</span></Link></div></section>
   <section className="home-photos" aria-labelledby="offscreen-title"><div className="section-heading"><div><p className="eyebrow">TAKING THE SCENIC ROUTE</p><h2 id="offscreen-title">Away from the keyboard<span className="mint">.</span></h2></div><Link className="quiet-link" href="/field-notes">Field notes <span>↗</span></Link></div><div className="photo-grid">{fieldNotes.map(note=><Link className="photo-card" href={`/field-notes/${note.slug}`} key={note.slug}><PhotoArt art={note.art} label={note.title}/><h3>{note.title}<span>↗</span></h3></Link>)}</div><p className="content-note">A few sample frames for now. Photography from Unsplash; credits in each story.</p></section>
  </div>
 </main>;
}
